#com.cosmos.sns와 하위 패키지 로그 레벨 설정
logging:
  level:
    com.cosmos.sns: debug
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
